import { NewsHeader } from "@/components/news-header"
import { NewsFooter } from "@/components/news-footer"

export default function About() {
    return (
        <div className="min-h-screen bg-background">
            <NewsHeader />
            <div className="space-y-12 px-8 py-8 mx-auto">
                <section className="space-y-4">
                    <h1 className="text-2xl font-bold">サイト情報</h1>
                    <p>
                        当サイトは、生成AIを利用して1日の主要ニュースを要約したサイトです。各ソースで報じられたニュースを日本語で簡潔にまとめることで、1日のニュースの理解をより容易にすることを目的としています。
                    </p>
                    <p>
                        要約の作成にはOpenAIを利用しています。
                    </p>
                    <p>
                        AIが生成した記事の内容については、著作権に配慮し、引用された範囲内で利用するよう努めています。ただし、人工知能によって生成された記事であるため、不適切な内容が含まれる可能性があります。そのようなケースをお知りになられた場合はご連絡ください。
                    </p>
                    <p>
                        当サイトで提供される記事の内容に関しては、最善を尽くして正確さを保つよう努めていますが、その正確性や完全性を保証するものではありません。また、当サイトの利用によって生じた損失や損害に対して、一切の責任を負わないことをご了承ください。
                    </p>
                </section>

                <section className="space-y-4">
                    <h1 className="text-2xl font-bold">Site Information</h1>
                    <p>
                        This website utilizes generative AI to provide summaries of the day's top news stories. By concisely translating and summarizing news from various sources into Japanese, we aim to make it easier to understand the day's key events.
                    </p>
                    <p>
                        We use OpenAI to generate these summaries.
                    </p>
                    <p>
                        We strive to respect copyright by ensuring that AI-generated articles stay within the bounds of proper citation. However, since the content is generated by artificial intelligence, there may be instances of inappropriate or inaccurate content. If you notice such cases, please contact us.
                    </p>
                    <p>
                        While we make every effort to ensure the accuracy of the articles provided on this site, we do not guarantee their completeness or correctness. Please note that we are not liable for any losses or damages resulting from the use of this website.
                    </p>

                </section>

            </div>
            <NewsFooter />
        </div>
    );
}
